### ISSUE TITLE
Should we have SCSS settings in editorconfig?

### ISSUE THREAD

**Issue by marcaddeo** [oomphinc/drupal-scaffold#13]
We probably should. We don't currently.

**Comment by nathandentzau** [comment]
10-4

**Comment by nathandentzau** [comment]
prolly js too

**Comment by nathandentzau** [comment]
@johncionci tossing this one your direction.

**Comment by johncionci** [comment]
@nathandentzau I think anything for SCSS/JS is already covered by the defaults.

**Comment by marcaddeo** [comment]
Hmmm. Not sure why I opened this now :/
