### ISSUE TITLE
Gulp has no default task

### ISSUE THREAD

**Issue by marcaddeo** [oomphinc/drupal-scaffold#16]
When running `lando gulp` you get the following:

```bash
± lando gulp
[14:28:24] Using gulpfile /app/gulpfile.js
[14:28:24] Task 'default' is not in your gulpfile
[14:28:24] Please check the documentation for proper gulpfile formatting
```

Should we add a default task that just pipes to the build task? Or do we want the explicit behavior we have now of having to specify the task?

**Comment by johncionci** [comment]
I think that we had talked about waiting until it was further fleshed out and we could add one. I would say that it should be minimal, maybe just a `compile & watch` because the more explicit tasks we have sorta "forces" people to review the file more IMO.
