### ISSUE TITLE
Update Lando version used by Travis

### ISSUE THREAD

**Issue by syzygy333** [oomphinc/drupal-scaffold#24]
Lando is pretty limited when it comes to what versions of Node it supports with each release (https://docs.devwithlando.io/tutorials/node.html).

Right now, Travis deploys using the beta47 version of Lando. I've updated the Lando that I use locally to the newest rc release. These newer releases change which versions of Node are supported; whereas beta supported 8.9, rc6 supports Node 10 at the oldest, and even its Legacy version support only supports 8 and 8.14.

So, to get my local environments to work, I had to update the version of Node specified in my lando.yml from 8.9 to 10, but I can't commit that change because the Travis version of Lando doesn't support Node 10 and that will stop the build from completing.

Right now it seems like there's a new rc version every other day, so it's probably smart to wait until there's a bit more stability there, but soon we should be thinking about not using the beta version anymore.

**Comment by marcaddeo** [comment]
Ah, I see what you mean as to why it would break deployments. Makes sense.

And yeah, I think I agree.. Maybe we should just endure what we currently have until they actually release `1.0.0` which is HOPEFULLY soon.

**Comment by nathandentzau** [comment]
I'm going to close this as it's not specific to this project but to another project in the oomphinc org.
