### ISSUE TITLE
You are about to DROP all tables in your 'drupal8' database. Do you want to continue?

### ISSUE THREAD

**Issue by nigelwhite** [oomphinc/drupal-scaffold#26]
As per your docs I did -
$ composer create-project oomphinc/drupal-scaffold my-project.tld --no-interaction
$ lando start && lando drush site-install standard --account-pass=admin

This got me to BOOMSHAKALAKA!!! and the project urls, but then -
You are about to DROP all tables in your 'drupal8' database. Do you want to continue? (yes/no) [yes]:

I tried both yes and no, but they both lead to The website encountered an unexpected error.

I am familiar with Lando but this is my first time to try your scaffold, so I am not sure what should be happening.

BTW this sounds an amazing resource, thanks.... Hope I can get it working. Thanks

Ubuntu 18.04, Lando v3.0.0-beta.47

**Comment by nathandentzau** [comment]
Hi @nigelwhite could you create a `/web/sites/default/settings.local.php` file with the following in it:

```php
<?php

$config['system.logging']['error_level'] = 'verbose';
```

Then visit the website in Lando, this should give you a stack trace that we can debug further. Please post the output.

Thanks!

**Comment by nigelwhite** [comment]
$ lando start
gave the following, (It didn't throw up You are about to DROP all tables in your 'drupal8' database. Do you want to continue?)

The website encountered an unexpected error. Please try again later.</br></br><em class="placeholder">Symfony\Component\HttpKernel\Exception\NotFoundHttpException</em>:  in <em class="placeholder">Drupal\Core\PathProcessor\PathProcessorFront-&gt;processInbound()</em> (line <em class="placeholder">43</em> of <em class="placeholder">core/lib/Drupal/Core/PathProcessor/PathProcessorFront.php</em>). <pre class="backtrace">Drupal\Core\PathProcessor\PathProcessorManager-&gt;processInbound(&#039;/&#039;, Object) (Line: 171)
Drupal\Core\Routing\RouteProvider-&gt;getRouteCollectionForRequest(Object) (Line: 239)
Drupal\Core\Routing\Router-&gt;getInitialRouteCollection(Object) (Line: 123)
Drupal\Core\Routing\Router-&gt;matchRequest(Object) (Line: 92)
Drupal\Core\Routing\AccessAwareRouter-&gt;matchRequest(Object) (Line: 115)
Symfony\Component\HttpKernel\EventListener\RouterListener-&gt;onKernelRequest(Object, &#039;kernel.request&#039;, Object)
call_user_func(Array, Object, &#039;kernel.request&#039;, Object) (Line: 111)
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher-&gt;dispatch(&#039;kernel.request&#039;, Object) (Line: 127)
Symfony\Component\HttpKernel\HttpKernel-&gt;handleRaw(Object, 1) (Line: 68)
Symfony\Component\HttpKernel\HttpKernel-&gt;handle(Object, 1, 1) (Line: 57)
Drupal\Core\StackMiddleware\Session-&gt;handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\KernelPreHandle-&gt;handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware-&gt;handle(Object, 1, 1) (Line: 52)
Drupal\Core\StackMiddleware\NegotiationMiddleware-&gt;handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel-&gt;handle(Object, 1, 1) (Line: 693)
Drupal\Core\DrupalKernel-&gt;handle(Object) (Line: 19)
</pre>

$ lando start && lando drush site-install standard --account-pass=admin
did throw up You are about to DROP all tables in your 'drupal8' database. Do you want to continue? (yes/no) [yes]: and the following

The website encountered an unexpected error. Please try again later.</br></br><em class="placeholder">Symfony\Component\HttpKernel\Exception\NotFoundHttpException</em>:  in <em class="placeholder">Drupal\Core\PathProcessor\PathProcessorFront-&gt;processInbound()</em> (line <em class="placeholder">43</em> of <em class="placeholder">core/lib/Drupal/Core/PathProcessor/PathProcessorFront.php</em>). <pre class="backtrace">Drupal\Core\PathProcessor\PathProcessorManager-&gt;processInbound(&#039;/&#039;, Object) (Line: 171)
Drupal\Core\Routing\RouteProvider-&gt;getRouteCollectionForRequest(Object) (Line: 239)
Drupal\Core\Routing\Router-&gt;getInitialRouteCollection(Object) (Line: 123)
Drupal\Core\Routing\Router-&gt;matchRequest(Object) (Line: 92)
Drupal\Core\Routing\AccessAwareRouter-&gt;matchRequest(Object) (Line: 115)
Symfony\Component\HttpKernel\EventListener\RouterListener-&gt;onKernelRequest(Object, &#039;kernel.request&#039;, Object)
call_user_func(Array, Object, &#039;kernel.request&#039;, Object) (Line: 111)
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher-&gt;dispatch(&#039;kernel.request&#039;, Object) (Line: 127)
Symfony\Component\HttpKernel\HttpKernel-&gt;handleRaw(Object, 1) (Line: 68)
Symfony\Component\HttpKernel\HttpKernel-&gt;handle(Object, 1, 1) (Line: 57)
Drupal\Core\StackMiddleware\Session-&gt;handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\KernelPreHandle-&gt;handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware-&gt;handle(Object, 1, 1) (Line: 52)
Drupal\Core\StackMiddleware\NegotiationMiddleware-&gt;handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel-&gt;handle(Object, 1, 1) (Line: 693)
Drupal\Core\DrupalKernel-&gt;handle(Object) (Line: 19)
</pre>

Thanks

**Comment by marcaddeo** [comment]
Hey @nigelwhite, I'm still running `3.0.0-beta.47` myself, but on macOS. I just ran the following commands and didn't have any issues:

```
$ composer create-project oomphinc/drupal-scaffold my-project.tld --no-interaction
$ cd my-project.tld
$ lando start && lando drush site-install standard --account-pass=admin
```

When it prompted me about DROPing all of the tables, I answered "yes".

I just want to check since it's not explicitly stated in our documentation, did you `cd` into the `my-project.tld` that was created by the `composer create-project` command?

**Comment by nigelwhite** [comment]
Ah, my bad. I just cleared a load of space on my hard drive and tried afresh. This time no problem.

Thanks both. Thanks also for clarifying that I should answer "yes" to DROP all tables - it sounds kind of scary, so its good to know that "yes" is correct.

**Comment by marcaddeo** [comment]
Glad you got it working @nigelwhite!
