### ISSUE TITLE
Document what needs to be edited for project setup

### ISSUE THREAD

**Issue by marcaddeo** [oomphinc/drupal-scaffold#3]
Currently the README just says do `composer create-project` and `lando start`, but before doing `lando start` we should have some customizations in place on a per-project basis. This should be documented.

For instance, the `.lando.yml` file needs to, at the very least, be updated for the project name.
We should also note that the `.travis.yml` file needs to be updated in order to put deployments into place.

**Comment by raubin** [comment]
Closing since the README has seen some updates and some aspects of the set up have changed.
