### ISSUE TITLE
Add Git Hooks for "on Push" commands

### ISSUE THREAD

**Issue by johncionci** [oomphinc/drupal-scaffold#42]
Add functionality to run commands locally as they would on Travis, only when doing a "git push"
@codeclarified @ben-hamelin @jbenholt @syzygy333 ... for some reason I can tag Kaleem.

**Comment by ben-hamelin** [comment]
@johncionci Are we ok to close this?

**Comment by johncionci** [comment]
I would still like to see this happen but Im sure it can be closed since theres been no movement since '19
