### ISSUE TITLE
Add Drupal Console support

### ISSUE THREAD

**Issue by ben-hamelin** [oomphinc/drupal-scaffold#45]
Add Drupal console support, including composer dependency and lando.yml configuration.

Update README to cover any needed setup (may require global install of drupal console?)

https://drupalconsole.com/docs/en/getting/composer
https://github.com/lando/lando/issues/381

@johncionci @codeclarified @syzygy333 @jbenholt @kclarkson

**Comment by raubin** [comment]
Our team discussed this internally and have decided to move forward with this enhancement since a lot of folks here use this tool and adding it will save some steps.
