### ISSUE TITLE
Need an outline for contributing to the project

### ISSUE THREAD

**Issue by raubin** [oomphinc/drupal-scaffold#46]
We need some documentation for public and team that outlines how folks can contribute to the project and what the intent of the project is so folks know what they should and shouldn't suggest for feature enhancements.

**Comment by hotwebmatter** [comment]
@raubin This is exactly the type of project I would consider taking on _pro bono_, because I feel that it plays to my strength (as a copy editor for documentation projects) and will also help me to learn best practices for D8 / D9 Composer-based project tooling.
