### ISSUE TITLE
Gulp to build faster

### ISSUE THREAD

**Issue by kbeck303** [oomphinc/drupal-scaffold#52]
Gulp can take upwards of 20-40 seconds per local build. 

Add @jbenholt 's fix for bcbs.com gulp slowness https://github.com/oomphinc/bcbs.com/pull/1490 to the scaffold.

**Comment by ben-hamelin** [comment]
@jordan-caldwell cc/ @kbeck303 Thinking we can close with webpack added now.

**Comment by johncionci** [comment]
Closing - Gulp has been removed.
