### ISSUE TITLE
[warning] Use of undefined constant on new site install

### ISSUE THREAD

**Issue by raubin** [oomphinc/drupal-scaffold#71]
This line is causing a PHP warning on new install: 

https://github.com/oomphinc/drupal-scaffold/blob/8a3150170d202aa5cc2b52a7c5692e0eb22b13d1/web/sites/default/settings.php#L786

The warning:
``` [warning] Use of undefined constant CONFIG_SYNC_DIRECTORY - assumed 'CONFIG_SYNC_DIRECTORY' (this will throw an Error in a future version of PHP) settings.php:786```

@ben-hamelin - I think this addition is something in one of your recent merges. Is it needed? I don't see `$config_directories` used in this file, so I'm wondering if maybe this was for something in a local settings file.

If it can be removed, I'll open a PR, just let me know!

**Comment by ben-hamelin** [comment]
@raubin Yes I think these two lines can be removed: 
`
// This setting is specific to Lando.
$config_directories[CONFIG_SYNC_DIRECTORY] = '/app/config/common';
`
I believe this was being maintained for specific vendors but it doesn't make sense here in the Lando conditional.
See also: https://www.drupal.org/node/3018145
