### ISSUE TITLE
README updates: call out dependencies sooner in the doc

### ISSUE THREAD

**Issue by raubin** [oomphinc/drupal-scaffold#8]
Looks like the only 3 are Composer, Docker and Lando, and Lando will prompt to install Docker if it isn't already there.

**Comment by nathandentzau** [comment]
@raubin composer should not be a dependency as it should be run _inside_ of `appserver` container using `lando composer`.

**Comment by raubin** [comment]
@nathandentzau - the first command for the installation instructions is to run composer

**Comment by marcaddeo** [comment]
@raubin,

Composer is a dependency only for creating a project. After that, anyone using the project doesn't technically require having Composer installed on their system.

The documentation in `docs/` is aimed to document the project that is created by the scaffold, and the `README` documents how to use the scaffold to create a project.
