### ISSUE TITLE
Change default branch to `main`

### ISSUE THREAD

**Issue by ben-hamelin** [oomphinc/drupal-scaffold#89]
The `main` branch will become the new default branch. Prior to completely removing the `master` branch we need to be sure we don't have any CI/CD dependencies that rely on that branch.

Tagging @edaemon , @pfrilling , @raubin , @sonnentag

**Comment by edaemon** [comment]
I have switched the default branch to `main`. There is no CI/CD for this project currently so there's no concern there. There is only one open PR (#6) that needs to be updated, but it's quite old so it may not be relevant anymore. Once that PR is closed the `master` branch can be removed.
